import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { getCareerDoc, getInterestsDoc, getprofileDoc } from "./components/Shared/Fetch/FetchDoc";
import ComponentSwitcher from "./components/Component Switcher/Component-Switcher";

const profile = await getprofileDoc();
const career = await getCareerDoc();
const interests = await getInterestsDoc();

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Jason Alcock CV",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const documents = [
		profile,
		career,
		interests
	]
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-[#afcbff] antialiased`}
      >
          {children}
      </body>
    </html>
  );
}
